In [23]:
import numpy as np
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

In [2]:
from importlib import reload

In [10]:
import naive_bayes
reload(naive_bayes)
from naive_bayes import GaussianNaiveBayes

In [4]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [6]:
X.shape, y.shape

((150, 4), (150,))

### Check personal package

In [17]:
my_model = GaussianNaiveBayes()
my_model.fit(X, y)
my_predict_probs = my_model.predict_proba(X)
my_predict = my_model.predict(X)

In [12]:
my_model.Mu_

array([[ 5.006,  3.418,  1.464,  0.244],
       [ 5.936,  2.77 ,  4.26 ,  1.326],
       [ 6.588,  2.974,  5.552,  2.026]])

In [13]:
my_model.Sigma_

array([[ 0.121764,  0.142276,  0.029504,  0.011264],
       [ 0.261104,  0.0965  ,  0.2164  ,  0.038324],
       [ 0.396256,  0.101924,  0.298496,  0.073924]])

In [28]:
np.random.seed(1)
idx = np.random.choice(np.arange(len(X)), size=10)

In [29]:
my_predict_probs[idx,:]

array([[  1.00000000e+000,   3.20343686e-018,   1.12989380e-025],
       [  5.79617468e-220,   5.01445954e-009,   9.99999995e-001],
       [  1.06618094e-120,   9.27077058e-001,   7.29229423e-002],
       [  1.30860648e-169,   1.90227549e-003,   9.98097725e-001],
       [  2.19789265e-130,   7.12645155e-001,   2.87354845e-001],
       [  4.63166801e-042,   9.99998762e-001,   1.23794175e-006],
       [  4.84173585e-234,   1.64602450e-010,   1.00000000e+000],
       [  1.61328551e-181,   7.01805631e-004,   9.99298194e-001],
       [  2.12412637e-071,   9.99807026e-001,   1.92973805e-004],
       [  3.68931836e-153,   4.86199307e-001,   5.13800693e-001]])

In [30]:
my_predict[idx]

array([0, 2, 1, 2, 1, 1, 2, 2, 1, 2])

### Check scikit-learn GaussianNB

In [18]:
sk_model = GaussianNB()
sk_model.fit(X, y)
sk_predict_probs = sk_model.predict_proba(X)
sk_predict = sk_model.predict(X)

In [15]:
sk_model.theta_

array([[ 5.006,  3.418,  1.464,  0.244],
       [ 5.936,  2.77 ,  4.26 ,  1.326],
       [ 6.588,  2.974,  5.552,  2.026]])

In [16]:
sk_model.sigma_

array([[ 0.121764,  0.142276,  0.029504,  0.011264],
       [ 0.261104,  0.0965  ,  0.2164  ,  0.038324],
       [ 0.396256,  0.101924,  0.298496,  0.073924]])

In [25]:
np.random.seed(1)
idx = np.random.choice(np.arange(len(X)), size=10)

In [26]:
sk_predict_probs[idx, :]

array([[  1.00000000e+000,   3.20344249e-018,   1.12989524e-025],
       [  5.79667973e-220,   5.01446575e-009,   9.99999995e-001],
       [  1.06622383e-120,   9.27077052e-001,   7.29229479e-002],
       [  1.30868299e-169,   1.90227600e-003,   9.98097724e-001],
       [  2.19798649e-130,   7.12645144e-001,   2.87354856e-001],
       [  4.63173354e-042,   9.99998762e-001,   1.23794211e-006],
       [  4.84219075e-234,   1.64602693e-010,   1.00000000e+000],
       [  1.61337601e-181,   7.01805717e-004,   9.99298194e-001],
       [  2.12417952e-071,   9.99807026e-001,   1.92973847e-004],
       [  3.68949024e-153,   4.86199285e-001,   5.13800715e-001]])

In [27]:
sk_predict[idx]

array([0, 2, 1, 2, 1, 1, 2, 2, 1, 2])